*BREAK EX_PATIL.
TOTAL_DEBIT = 0.
TOTAL_CREDIT = 0.


SELECT SINGLE name2 FROM lfa1 INTO wa_vendorbal-name2
                      WHERE lifnr = wa_vendorbal-lifnr.

CONCATENATE WA_vendorBAL-HOUSE_NUM1
 WA_vendorBAL-STREET
 WA_VENDORBAL-str_suppl1
  WA_VENDORBAL-str_suppl1 INTO lv_addr SEPARATED BY space.

CONDENSE lv_addr.
CONCATENATE WA_VENDORBAL-NAME1 WA_VENDORBAL-NAME2
INTO lv_addr1 SEPARATED BY space.
CONDENSE lv_addr1.


CONCATENATE WA_VENDORBAL-ORT02
WA_VENDORBAL-ORT01 '-'
WA_VENDORBAL-PSTLZ INTO lv_addr2 SEPARATED BY space.
CONDENSE lv_addr2 .

IF WA_VENDORBAL-CLBAL LT 0.
WA_VENDORBAL-CLBAL = WA_VENDORBAL-CLBAL * -1.

LV_CR_DR = 'Cr'.

else.

LV_CR_DR = 'Dr'.
ENDIF.

