
REPORT  ZIN1_BAL_CONF.

INCLUDE <ICON>.
TYPE-POOLS : SLIS, ABAP.
TABLES : BSID, BSAD, BKPF, BSEG, SKAT, KNA1, PAYR, CSKT, CEPCT,BSIK.

TYPES: BEGIN OF STR_FINAL,
         ICON   TYPE ICON_D,
         BUKRS  TYPE BSID-BUKRS,
         KUNNR  TYPE BSID-KUNNR,
         NAME1  TYPE KNA1-NAME1,
         UMSKS  TYPE BSID-UMSKS,
         UMSKZ  TYPE BSID-UMSKZ,
         AUGDT  TYPE BSID-AUGDT,
         AUGBL  TYPE BSID-AUGBL,
         ZUONR  TYPE BSID-ZUONR,
         GJAHR  TYPE BSID-GJAHR,
         BELNR  TYPE BSID-BELNR,
         BUZEI  TYPE BSID-BUZEI,
         BUDAT  TYPE BSID-BUDAT,
         BLDAT  TYPE BSID-BLDAT,
         XBLNR  TYPE BSID-XBLNR,
         BLART  TYPE BSID-BLART,
         BSCHL  TYPE BSID-BSCHL,
         SHKZG  TYPE BSID-SHKZG,
         GSBER  TYPE BSID-GSBER,
         SGTXT  TYPE BSID-SGTXT,
         HKONT  TYPE BSID-HKONT,
         ZFBDT  TYPE BSID-ZFBDT,
         KOSTL  TYPE BSID-KOSTL,
         PRCTR  TYPE BSID-PRCTR,
         BUPLA  TYPE BSID-BUPLA,
         SECCO  TYPE BSID-SECCO,
         BKTXT  TYPE BKPF-BKTXT,
         CHECT  TYPE PAYR-CHECT,
         TEXT   TYPE BSID-SGTXT,
         CREDIT TYPE BSID-DMBTR,
         DEBIT  TYPE BSID-DMBTR,
         CNAME  TYPE CSKT-KTEXT,
         PNAME  TYPE CEPCT-KTEXT,
         SAKNR  TYPE SKAT-SAKNR,
         GLT20  TYPE SKAT-TXT20,
         GLT50  TYPE SKAT-TXT50,
         TXT20  TYPE SKAT-TXT20,
         TXT50  TYPE SKAT-TXT50,
       END OF STR_FINAL.

TYPES : BEGIN OF STR_BAL,
          KUNNR  TYPE BSID-KUNNR,
          NAME1  TYPE KNA1-NAME1,
          STRAS  TYPE KNA1-STRAS,
          ORT01  TYPE KNA1-ORT01,
          PSTLZ  TYPE KNA1-PSTLZ,
          OPBAL  TYPE BSID-DMBTR,
          CLBAL  TYPE BSID-DMBTR,
          OPDATE TYPE SY-DATUM,
          CLDATE TYPE SY-DATUM,
        END OF STR_BAL.

TYPES : BEGIN OF STR_BSID,
          BUKRS TYPE BSID-BUKRS,
          KUNNR TYPE BSID-KUNNR,
          UMSKS TYPE BSID-UMSKS,
          UMSKZ TYPE BSID-UMSKZ,
          AUGDT TYPE BSID-AUGDT,
          AUGBL TYPE BSID-AUGBL,
          ZUONR TYPE BSID-ZUONR,
          GJAHR TYPE BSID-GJAHR,
          BELNR TYPE BSID-BELNR,
          BUZEI TYPE BSID-BUZEI,
          BUDAT TYPE BSID-BUDAT,
          BLDAT TYPE BSID-BLDAT,
          XBLNR TYPE BSID-XBLNR,
          BLART TYPE BSID-BLART,
          BSCHL TYPE BSID-BSCHL,
          SHKZG TYPE BSID-SHKZG,
          GSBER TYPE BSID-GSBER,
          DMBTR TYPE BSID-DMBTR,
          WRBTR TYPE BSID-WRBTR,
          SGTXT TYPE BSID-SGTXT,
          HKONT TYPE BSID-HKONT,
          ZFBDT TYPE BSID-ZFBDT,
          KOSTL TYPE BSID-KOSTL,
          PRCTR TYPE BSID-PRCTR,
          BUPLA TYPE BSID-BUPLA,
          SECCO TYPE BSID-SECCO,
        END OF STR_BSID.

TYPES : BEGIN OF STR_BKPF,
          BUKRS TYPE BKPF-BUKRS,
          BELNR TYPE BKPF-BELNR,
          GJAHR TYPE BKPF-GJAHR,
          BKTXT TYPE BKPF-BKTXT,
        END OF STR_BKPF.

TYPES : BEGIN OF STR_BSEG,
          BUKRS TYPE BSEG-BUKRS,
          BELNR TYPE BSEG-BELNR,
          GJAHR TYPE BSEG-GJAHR,
          BUZEI TYPE BSEG-BUZEI,
          DMBTR TYPE BSEG-DMBTR,
          KOSTL TYPE BSEG-KOSTL,
          HKONT TYPE BSEG-HKONT,
          KUNNR TYPE BSEG-KUNNR,
          LIFNR TYPE BSEG-LIFNR,
          PRCTR TYPE BSEG-PRCTR,
        END OF STR_BSEG.

TYPES : BEGIN OF STR_SKAT,
          SPRAS TYPE SKAT-SPRAS,
          KTOPL TYPE SKAT-KTOPL,
          SAKNR TYPE SKAT-SAKNR,
          TXT20 TYPE SKAT-TXT20,
          TXT50 TYPE SKAT-TXT50,
        END OF STR_SKAT.

TYPES : BEGIN OF STR_KNA1,
          KUNNR TYPE KNA1-KUNNR,
          NAME1 TYPE KNA1-NAME1,
          ORT01 TYPE KNA1-ORT01,
          PSTLZ TYPE KNA1-PSTLZ,
          STRAS TYPE KNA1-STRAS,
          REGIO TYPE KNA1-REGIO,
          LAND1 TYPE KNA1-LAND1,
          TELF1 TYPE KNA1-TELF1,
          ADRNR TYPE KNA1-ADRNR,
        END OF STR_KNA1.
TYPES: BEGIN OF TT_ADRC,
         ADDRNUMBER TYPE ADRC-ADDRNUMBER,
         STR_SUPPL1 TYPE ADRC-STR_SUPPL1,
         STR_SUPPL2 TYPE ADRC-STR_SUPPL2,
         STR_SUPPL3 TYPE ADRC-STR_SUPPL3,
       END OF TT_ADRC.
DATA: GT_ADRC TYPE TABLE OF TT_ADRC,
      GS_ADRC TYPE TT_ADRC.
TYPES : BEGIN OF STR_T005T,
          SPRAS TYPE T005T-SPRAS,
          LAND1 TYPE T005T-LAND1,
          LANDX TYPE T005T-LANDX,
        END OF STR_T005T.

TYPES : BEGIN OF STR_T005U,
          SPRAS TYPE T005U-SPRAS,
          BLAND TYPE T005U-BLAND,
          BEZEI TYPE T005U-BEZEI,
        END OF STR_T005U.

TYPES : BEGIN OF OP_BAL,
          KUNNR TYPE KNA1-KUNNR,
          NAME1 TYPE KNA1-NAME1,
          STRAS TYPE KNA1-STRAS,
          ORT01 TYPE KNA1-ORT01,
          PSTLZ TYPE KNA1-PSTLZ,
          OPBAL TYPE BSID-DMBTR,
          CLBAL TYPE BSID-DMBTR,
        END OF OP_BAL.

TYPES : BEGIN OF STR_PAYR,
          ZBUKR TYPE PAYR-ZBUKR,
          CHECT TYPE PAYR-CHECT,
          VBLNR TYPE PAYR-VBLNR,
          GJAHR TYPE PAYR-GJAHR,
        END OF STR_PAYR.

TYPES : BEGIN OF STR_CSKT,
          SPRAS TYPE CSKT-SPRAS,
          KOKRS TYPE CSKT-KOKRS,
          KOSTL TYPE CSKT-KOSTL,
          KTEXT TYPE CSKT-KTEXT,
          LTEXT TYPE CSKT-LTEXT,
        END OF STR_CSKT.

TYPES : BEGIN OF STR_CEPCT,
          SPRAS TYPE CEPCT-SPRAS,
          PRCTR TYPE CEPCT-PRCTR,
          KOKRS TYPE CEPCT-KOKRS,
          KTEXT TYPE CEPCT-KTEXT,
          LTEXT TYPE CEPCT-LTEXT,
        END OF STR_CEPCT.

DATA : FNAME TYPE RS38L_FNAM.

DATA : IT_BSAD         TYPE TABLE OF STR_BSID,
       WA_BSAD         TYPE STR_BSID,
       IT_BSID         TYPE TABLE OF STR_BSID,
       WA_BSID         TYPE STR_BSID,
       W_BSID          TYPE STR_BSID,
       IT_CUST_BAL     TYPE TABLE OF  STR_BSID,
       WA_CUST_BAL     TYPE  STR_BSID,
       IT_BKPF         TYPE TABLE OF STR_BKPF,
       WA_BKPF         TYPE STR_BKPF,
       IT_BSEG         TYPE TABLE OF STR_BSEG,
       WA_BSEG         TYPE STR_BSEG,
       IT_BSEGCCPC     TYPE TABLE OF STR_BSEG,
       WA_BSEGCCPC     TYPE STR_BSEG,
       IT_BSEGAC       TYPE TABLE OF STR_BSEG,
       WA_BSEGAC       TYPE STR_BSEG,
       IT_SKAT         TYPE TABLE OF STR_SKAT,
       WA_SKAT         TYPE STR_SKAT,
       IT_KNA1         TYPE TABLE OF STR_KNA1,
       WA_KNA1         TYPE STR_KNA1,
       IT_T005U        TYPE TABLE OF STR_T005U,
       WA_T005U        TYPE STR_T005U,
       IT_T005T        TYPE TABLE OF STR_T005T,
       WA_T005T        TYPE STR_T005T,
       IT_PAYR         TYPE TABLE OF STR_PAYR,
       WA_PAYR         TYPE STR_PAYR,
       IT_CSKT         TYPE TABLE OF STR_CSKT,
       WA_CSKT         TYPE STR_CSKT,
       IT_CEPCT        TYPE TABLE OF STR_CEPCT,
       WA_CEPCT        TYPE STR_CEPCT,
       IT_CUSTBAL      TYPE TABLE OF ZIN1_CUSTBAL,
       IT_CUSTBAL_COPY TYPE TABLE OF ZIN1_CUSTBAL,
       WA_CUSTBAL      TYPE ZIN1_CUSTBAL,
       IT_FINAL        TYPE TABLE OF ZIN1_CUST_LEDGER,
       IT_FINAL_COPY   TYPE TABLE OF ZIN1_CUST_LEDGER,
       WA_FINAL        TYPE ZIN1_CUST_LEDGER,
       CR_CHK          TYPE BSEG-DMBTR,
       DR_CHK          TYPE BSEG-DMBTR,
       IT_FCAT         TYPE SLIS_T_FIELDCAT_ALV,
       WA_FCAT         TYPE SLIS_FIELDCAT_ALV,
       IT_SORT         TYPE SLIS_T_SORTINFO_ALV,
       WA_SORT         TYPE SLIS_SORTINFO_ALV,
       IT_EVENTS       TYPE SLIS_T_EVENT,
       WA_EVENTS       TYPE SLIS_ALV_EVENT.
DATA : LV_MSG TYPE STRING.

DATA : EBELN TYPE EBELN .
DATA : RFBSK TYPE VBRK-RFBSK.
*       WA_VBRK TYPE VBRK.
*DATA : fname TYPE tdsfname .
DATA : IT_EKKO1 TYPE EKKO OCCURS 0 WITH HEADER LINE .
DATA: PARAMS   TYPE SSFCOMPOP,
      LV_VBELN TYPE VBRK-VBELN.

DATA: T_ADR6 TYPE TABLE OF ADR6,
      W_ADR6 TYPE ADR6,

      DAYS   TYPE  I.

DATA: T_ADR2 TYPE TABLE OF ADR2,
      W_ADR2 TYPE ADR2,
      W_KNA1 TYPE KNA1.

DATA: CPARAM TYPE SSFCTRLOP,
      OUTOP  TYPE SSFCOMPOP.

DATA: TAB_OTF_DATA  TYPE SSFCRESCL,
      PDF_TAB       LIKE TLINE OCCURS 0 WITH HEADER LINE,
      TAB_OTF_FINAL TYPE ITCOO OCCURS 0 WITH HEADER LINE,
      FILE_SIZE     TYPE I,
      BIN_FILESIZE  TYPE I,
      FILE_NAME     TYPE STRING,
      FULL_PATH     TYPE STRING,
      DATE(10)      TYPE C,
      LV_DATE1      TYPE STRING,
      LT_BCS_PDF    TYPE   SOLIX_TAB.   "" + NC

***********************************************************************************************************
"Sending Mail to Customer.
***********************************************************************************************************


* INTERNAL TABLE DECLARATIONS
DATA: I_OTF       TYPE ITCOO OCCURS 0 WITH HEADER LINE,
      I_TLINE     LIKE TLINE OCCURS 0 WITH HEADER LINE,
      I_RECEIVERS TYPE TABLE OF SOMLRECI1 WITH HEADER LINE,
      I_RECORD    LIKE SOLISTI1 OCCURS 0 WITH HEADER LINE,
* OBJECTS TO SEND MAIL.
      I_OBJPACK   LIKE SOPCKLSTI1 OCCURS 0 WITH HEADER LINE,
      I_OBJTXT    LIKE SOLISTI1 OCCURS 0 WITH HEADER LINE,
      I_OBJBIN    LIKE SOLISTI1 OCCURS 0 WITH HEADER LINE,
      I_RECLIST   LIKE SOMLRECI1 OCCURS 0 WITH HEADER LINE,
* WORK AREA DECLARATIONS
      WA_OBJHEAD  TYPE SOLI_TAB,
      W_CTRLOP    TYPE SSFCTRLOP,
      W_COMPOP    TYPE SSFCOMPOP,
      W_RETURN    TYPE SSFCRESCL,
      WA_DOC_CHNG TYPE SODOCCHGI1,
      W_DATA      TYPE SODOCCHGI1,
      WA_BUFFER   TYPE STRING, "TO CONVERT FROM 132 TO 255
* VARIABLES DECLARATIONS
      V_FORM_NAME TYPE RS38L_FNAM,
      V_LEN_IN    TYPE I,
      V_LEN_OUT   LIKE SOOD-OBJLEN,
      V_LEN_OUTN  TYPE I,
      V_LINES_TXT TYPE I,
      V_LINES_BIN TYPE I,
      SUBJECT(50) TYPE C,
      ATTACH(50)  TYPE C.
*    DATA : RATE TYPE TCURR-UKURS,
*        V_AMOUNT TYPE BSEG-WRBTR,"bsik-dmbtr.
*        DEB_AMT TYPE BSEG-WRBTR."bsik-dmbtr.

DATA : LV_ADRNR     TYPE KNA1-ADRNR,
       LV_SMTP_ADDR TYPE ADR6-SMTP_ADDR.

DATA : LV_TEXT   TYPE STRING,
       POSTDATE1 TYPE CHAR15.

SELECTION-SCREEN: BEGIN OF BLOCK SEL WITH FRAME TITLE TEXT-001.
  PARAMETERS     : COMPCODE TYPE BSID-BUKRS ."OBLIGATORY DEFAULT 'IN1'.
  SELECT-OPTIONS : PROCENT  FOR BSID-PRCTR ."MODIF ID ID1.
  SELECT-OPTIONS : CUSTNO   FOR BSID-KUNNR ."MODIF ID ID2.
  SELECT-OPTIONS : VENDORNO FOR BSIK-LIFNR.
  PARAMETERS: POSTDATE TYPE BSID-BUDAT OBLIGATORY ."NO-EXTENSION OBLIGATORY.
*SELECT-OPTIONS : POSTDATE FOR BSID-BUDAT NO-EXTENSION OBLIGATORY.
  PARAMETERS     : CURRENCY TYPE BSID-WAERS OBLIGATORY.
SELECTION-SCREEN: END OF BLOCK SEL.

SELECTION-SCREEN: BEGIN OF BLOCK SE WITH FRAME TITLE TEXT-002.
  PARAMETERS     : CUST TYPE BSID-UMSKZ RADIOBUTTON GROUP S1 ."DEFAULT 'X'. "MODIF ID ID1.
  PARAMETERS     : VEND TYPE BSID-UMSKZ RADIOBUTTON GROUP S1 ."MODIF ID ID2.
  PARAMETERS     : CHKB AS CHECKBOX.
SELECTION-SCREEN: END OF BLOCK SE.

DATA: R_CUSTNO  TYPE RANGE OF KNA1-KUNNR,
      LS_CUSTNO LIKE LINE OF R_CUSTNO.

LOOP AT CUSTNO INTO LS_CUSTNO.
  LS_CUSTNO-SIGN = 'I'.
  LS_CUSTNO-OPTION = 'EQ'.
  LS_CUSTNO-LOW = LS_CUSTNO-LOW.
  APPEND LS_CUSTNO TO R_CUSTNO.
ENDLOOP.

*AT SELECTION-SCREEN OUTPUT.

*LOOP AT SCREEN.
*
*IF cust = 'X'.
*
*IF screen-name = 'VENDORNO-LOW' OR screen-name = 'VENDORNO-HIGH'.
*screen-active = 0.
*SCREEN-required = 'X'.
*MODIFY SCREEN.
*ENDIF.
*
*ELSEIF vend   = 'X'.
*
*IF screen-name = 'CUSTNO-LOW' OR screen-name = 'CUSTNO-HIGH'.
*screen-active = 0.
*SCREEN-required = 'X'.
*MODIFY SCREEN.
*
*ENDIF.
*ENDIF.
*
*
*
*ENDLOOP.

AT SELECTION-SCREEN ON COMPCODE.
  DATA : P_WERKS TYPE WERKS_D VALUE 'IN1'.


*INITIALIZATION.
  .


START-OF-SELECTION.

  IF VENDORNO IS  INITIAL AND CUSTNO IS  INITIAL.
    MESSAGE 'Please fill atleast one Vendor or Customer' TYPE 'S' DISPLAY LIKE 'E'.
  ENDIF.

  IF CUST = 'X' AND CUSTNO IS NOT INITIAL.
    PERFORM SELECT_DATA.
    PERFORM DISPLAY.
  ENDIF.

  IF VEND = 'X' AND VENDORNO IS NOT INITIAL.
    INCLUDE ZIN1_ACCOUNT_STATEMENT_VEND.

  ENDIF.

END-OF-SELECTION.
*&---------------------------------------------------------------------*
*&      FORM  GET_DATA
*&---------------------------------------------------------------------*
*
*----------------------------------------------------------------------*
*
*----------------------------------------------------------------------*
FORM SELECT_DATA.

  IF CUST IS NOT INITIAL AND VENDORNO-LOW IS NOT INITIAL.

    MESSAGE 'Please Select Correct Radio Button' TYPE 'E' DISPLAY LIKE 'W'.

  ENDIF.

  DATA:
    IT_KEYBALANCE TYPE STANDARD TABLE OF BAPI3008_3,
    WA_KEYBALANCE TYPE BAPI3008_3,
    KEY_DATE      TYPE DATUM.

  SELECT BUKRS
         KUNNR
         UMSKS
         UMSKZ
         AUGDT
         AUGBL
         ZUONR
         GJAHR
         BELNR
         BUZEI
         BUDAT
         BLDAT
         XBLNR
         BLART
         BSCHL
         SHKZG
         GSBER
         DMBTR
         WRBTR
         SGTXT
         HKONT
         ZFBDT
         KOSTL
         PRCTR
         BUPLA
         SECCO
    FROM BSID
    INTO TABLE IT_BSID
    WHERE BUKRS EQ COMPCODE
     AND WAERS EQ CURRENCY
     AND KUNNR IN R_CUSTNO
     AND BUDAT LE POSTDATE
     AND PRCTR IN PROCENT.
*     AND BLART NE 'AB'.


  IF CUST IS NOT INITIAL AND VENDORNO-LOW IS NOT INITIAL.

    MESSAGE 'Please Select Correct Radio Button' TYPE 'E'.

  ENDIF.


  SELECT BUKRS
         KUNNR
         UMSKS
         UMSKZ
         AUGDT
         AUGBL
         ZUONR
         GJAHR
         BELNR
         BUZEI
         BUDAT
         BLDAT
         XBLNR
         BLART
         BSCHL
         SHKZG
         GSBER
         DMBTR
         WRBTR
         SGTXT
         HKONT
         ZFBDT
         KOSTL
         PRCTR
         BUPLA
         SECCO
    FROM BSAD
    INTO TABLE IT_BSAD
    WHERE BUKRS EQ COMPCODE
     AND WAERS EQ CURRENCY
     AND KUNNR IN CUSTNO
     AND BUDAT LE POSTDATE
*     AND AUGDT LE POSTDATE
    AND  AUGDT > POSTDATE
    AND PRCTR IN PROCENT.
  APPEND LINES OF IT_BSAD TO IT_BSID.
*     AND BLART NE 'AB'.
***DELETE IT_BSAD WHERE BUDAT > POSTDATE.

*  LOOP AT IT_BSAD INTO WA_BSAD." WHERE BLART = 'AB'.
*    SELECT SUM( DMBTR ) FROM BSAD INTO CR_CHK WHERE BELNR = WA_BSAD-BELNR AND KUNNR = WA_BSAD-KUNNR AND SHKZG = 'H'.
*    SELECT SUM( DMBTR ) FROM BSAD INTO DR_CHK WHERE BELNR = WA_BSAD-BELNR AND KUNNR = WA_BSAD-KUNNR AND SHKZG = 'S'.
*    IF CR_CHK = DR_CHK AND WA_BSAD-BELNR = WA_BSAD-AUGBL.
*      DELETE IT_BSAD WHERE BELNR = WA_BSAD-BELNR AND KUNNR = WA_BSAD-KUNNR.
*    ENDIF.
*  ENDLOOP.
*
*  APPEND LINES OF IT_BSAD TO IT_BSID.
  SORT IT_BSID ASCENDING BY KUNNR BUDAT BELNR.


  IF NOT IT_BSID IS INITIAL.
    SELECT BUKRS BELNR GJAHR BKTXT FROM BKPF INTO TABLE IT_BKPF FOR ALL ENTRIES IN IT_BSID
      WHERE BUKRS = IT_BSID-BUKRS AND BELNR = IT_BSID-BELNR AND GJAHR = IT_BSID-GJAHR.

    SELECT BUKRS BELNR GJAHR BUZEI DMBTR KOSTL HKONT KUNNR LIFNR PRCTR FROM BSEG INTO TABLE IT_BSEG FOR ALL ENTRIES IN IT_BSID
      WHERE BUKRS = IT_BSID-BUKRS AND BELNR = IT_BSID-BELNR AND GJAHR = IT_BSID-GJAHR. "#EC CI_NOORDER

    APPEND LINES OF IT_BSEG TO IT_BSEGCCPC.
    DELETE IT_BSEGCCPC WHERE KOSTL = '' AND PRCTR = ''.
    APPEND LINES OF IT_BSEG TO IT_BSEGAC.
    DELETE IT_BSEGAC WHERE KUNNR <> ''.
    SORT IT_BSEGAC DESCENDING BY BELNR DMBTR.
    DELETE ADJACENT DUPLICATES FROM IT_BSEGAC COMPARING BELNR.

    SELECT SPRAS KTOPL SAKNR TXT20 TXT50 FROM SKAT INTO TABLE IT_SKAT FOR ALL ENTRIES IN IT_BSEG
      WHERE  SPRAS = 'E' AND KTOPL = COMPCODE AND SAKNR = IT_BSEG-HKONT.

    SELECT KUNNR NAME1 ORT01 PSTLZ STRAS REGIO LAND1 TELF1 ADRNR FROM KNA1 INTO CORRESPONDING FIELDS OF TABLE IT_KNA1
      FOR ALL ENTRIES IN IT_BSID
      WHERE KUNNR = IT_BSID-KUNNR.
    SELECT  ADDRNUMBER
            STR_SUPPL1
            STR_SUPPL2
            STR_SUPPL3
            STREET
            HOUSE_NUM1
            LOCATION FROM ADRC INTO TABLE IT_ADRC
      FOR ALL ENTRIES IN IT_LFA1
       WHERE ADDRNUMBER = IT_LFA1-ADRNR.
    SELECT SPRAS LAND1 LANDX FROM T005T INTO TABLE IT_T005T FOR ALL ENTRIES IN IT_KNA1
                                                       WHERE LAND1 = IT_KNA1-LAND1 AND SPRAS = 'EN'.

    SELECT SPRAS BLAND BEZEI FROM T005U INTO TABLE IT_T005U FOR ALL ENTRIES IN IT_KNA1
      WHERE SPRAS = 'EN' AND BLAND = IT_KNA1-REGIO AND LAND1 = IT_KNA1-LAND1.

    SELECT ZBUKR CHECT VBLNR GJAHR FROM PAYR INTO TABLE IT_PAYR FOR ALL ENTRIES IN IT_BSID
      WHERE ZBUKR = IT_BSID-BUKRS AND VBLNR = IT_BSID-BELNR AND GJAHR = IT_BSID-GJAHR.

    SELECT SPRAS KOKRS KOSTL KTEXT LTEXT FROM CSKT INTO TABLE IT_CSKT FOR ALL ENTRIES IN IT_BSID
      WHERE SPRAS = 'E' AND KOKRS = COMPCODE AND KOSTL = IT_BSID-KOSTL.

    SELECT SPRAS KOKRS KOSTL KTEXT LTEXT FROM CSKT APPENDING TABLE IT_CSKT FOR ALL ENTRIES IN IT_BSEGCCPC
      WHERE SPRAS = 'E' AND KOKRS = COMPCODE AND KOSTL = IT_BSEGCCPC-KOSTL.

    SELECT SPRAS PRCTR KOKRS KTEXT LTEXT FROM CEPCT INTO TABLE IT_CEPCT FOR ALL ENTRIES IN IT_BSID
      WHERE SPRAS = 'E' AND KOKRS = COMPCODE AND PRCTR = IT_BSID-PRCTR.

    SELECT SPRAS PRCTR KOKRS KTEXT LTEXT FROM CEPCT APPENDING TABLE IT_CEPCT FOR ALL ENTRIES IN IT_BSEGCCPC
      WHERE SPRAS = 'E' AND KOKRS = COMPCODE AND PRCTR = IT_BSEGCCPC-PRCTR.
  ENDIF.

  LOOP AT IT_KNA1 INTO WA_KNA1.
    WA_CUSTBAL-KUNNR = WA_KNA1-KUNNR.
    WA_CUSTBAL-NAME1 = WA_KNA1-NAME1.
    WA_CUSTBAL-STRAS = WA_KNA1-STRAS.
    WA_CUSTBAL-ORT01 = WA_KNA1-ORT01.
    WA_CUSTBAL-PSTLZ = WA_KNA1-PSTLZ.
    WA_CUSTBAL-TELF1 = WA_KNA1-TELF1.
*        WA_CUSTBAL-telf2 = wa_kna1-telf2.
    READ TABLE IT_ADRC INTO LS_ADRC WITH KEY ADDRNUMBER = WA_KNA1-ADRNR.
    WA_CUSTBAL-STR_SUPPL1 = LS_ADRC-STR_SUPPL1.
    WA_CUSTBAL-STR_SUPPL2 = LS_ADRC-STR_SUPPL2.
    WA_CUSTBAL-STR_SUPPL3 = LS_ADRC-STR_SUPPL3.
    WA_CUSTBAL-STREET = LS_ADRC-STREET.
    WA_CUSTBAL-HOUSE_NUM1 = LS_ADRC-HOUSE_NUM1.
    WA_CUSTBAL-LOCATION = LS_ADRC-LOCATION.
    READ TABLE IT_T005T INTO WA_T005T WITH KEY LAND1 = WA_KNA1-LAND1.
    WA_CUSTBAL-LANDX = WA_T005T-LANDX.

    READ TABLE IT_T005U INTO WA_T005U WITH KEY BLAND = WA_KNA1-REGIO.
    WA_CUSTBAL-BEZEI = WA_T005U-BEZEI.

    CALL FUNCTION 'BAPI_AR_ACC_GETKEYDATEBALANCE'
      EXPORTING
        COMPANYCODE  = COMPCODE
        CUSTOMER     = WA_KNA1-KUNNR
        KEYDATE      = KEY_DATE
        BALANCESPGLI = ABAP_TRUE
        NOTEDITEMS   = ABAP_TRUE
      TABLES
        KEYBALANCE   = IT_KEYBALANCE.

    LOOP AT IT_KEYBALANCE INTO WA_KEYBALANCE.
      IF CURRENCY = WA_KEYBALANCE-CURRENCY.
        WA_CUSTBAL-OPBAL = WA_CUSTBAL-OPBAL + WA_KEYBALANCE-LC_BAL.
      ENDIF.
    ENDLOOP.
****************************************************
    IF CURRENCY EQ 'EUR' OR CURRENCY EQ 'USD'.
      CLEAR W_BSID.
      READ TABLE IT_BSID INTO W_BSID WITH KEY KUNNR = WA_CUSTBAL-KUNNR.
      CLEAR : CL_RATE,CL_AMOUNT,CL_BAL.
      SELECT SINGLE KURSF FROM BKPF INTO CL_RATE WHERE
          BUKRS = W_BSID-BUKRS AND BELNR = W_BSID-BELNR AND GJAHR = W_BSID-GJAHR.

      CALL FUNCTION 'CONVERT_CURRENCY_BY_RATE'
        EXPORTING
          FROM_AMOUNT   = WA_CUSTBAL-OPBAL
          FROM_CURRENCY = 'INR'
          FROM_FACTOR   = '1'
          RATE          = CL_RATE
          TO_CURRENCY   = CURRENCY
          TO_FACTOR     = '1'
        IMPORTING
          TO_AMOUNT     = CL_AMOUNT
*        EXCEPTIONS
*         NO_RATE_FOUND = 1
*         OTHERS        = 2
        .

      CL_BAL = CL_AMOUNT * 10.
      WA_CUSTBAL-OPBAL = CL_BAL.

      WA_CUSTBAL-CLBAL = WA_CUSTBAL-OPBAL.

    ELSE.
      WA_CUSTBAL-CLBAL = WA_CUSTBAL-OPBAL.
    ENDIF.

****************************************************

*    WA_CUSTBAL-CLBAL = WA_CUSTBAL-OPBAL.
*    WA_CUSTBAL-OPDATE = POSTDATE-LOW.
*    WA_CUSTBAL-CLDATE = POSTDATE-HIGH.
    WA_CUSTBAL-CLDATE = POSTDATE.
    APPEND WA_CUSTBAL TO IT_CUSTBAL.
    CLEAR: WA_CUSTBAL, IT_KEYBALANCE, WA_KNA1.
  ENDLOOP.

  LOOP AT IT_BSID INTO WA_BSID.
    WA_FINAL-BUKRS = WA_BSID-BUKRS.
    WA_FINAL-KUNNR = WA_BSID-KUNNR.
    WA_FINAL-UMSKS = WA_BSID-UMSKS.
    WA_FINAL-UMSKZ = WA_BSID-UMSKZ.
    WA_FINAL-AUGDT = WA_BSID-AUGDT.
    WA_FINAL-AUGBL = WA_BSID-AUGBL.
    WA_FINAL-GJAHR = WA_BSID-GJAHR.
    WA_FINAL-BELNR = WA_BSID-BELNR.
    WA_FINAL-BUZEI = WA_BSID-BUZEI.
    WA_FINAL-BUDAT = WA_BSID-BUDAT.
    WA_FINAL-BLDAT = WA_BSID-BLDAT.
    WA_FINAL-XBLNR = WA_BSID-XBLNR.
    WA_FINAL-BLART = WA_BSID-BLART.
    WA_FINAL-BSCHL = WA_BSID-BSCHL.
    WA_FINAL-SHKZG = WA_BSID-SHKZG.
    WA_FINAL-GSBER = WA_BSID-GSBER.
    WA_FINAL-HKONT = WA_BSID-HKONT.
    WA_FINAL-ZFBDT = WA_BSID-ZFBDT.
    WA_FINAL-KOSTL = WA_BSID-KOSTL.
    WA_FINAL-PRCTR = WA_BSID-PRCTR.
    WA_FINAL-BUPLA = WA_BSID-BUPLA.
    WA_FINAL-SECCO = WA_BSID-SECCO.
    WA_FINAL-WAERS = CURRENCY.
    CALL FUNCTION 'FI_CONVERT_FIRSTCHARS_TOUPPER'
      EXPORTING
        INPUT_STRING  = WA_BSID-SGTXT
        SEPARATORS    = ' -.,'
      IMPORTING
        OUTPUT_STRING = WA_FINAL-SGTXT.
    CALL FUNCTION 'FI_CONVERT_FIRSTCHARS_TOUPPER'
      EXPORTING
        INPUT_STRING  = WA_BSID-ZUONR
        SEPARATORS    = ' -.,'
      IMPORTING
        OUTPUT_STRING = WA_FINAL-ZUONR.

    IF WA_FINAL-SHKZG = 'S'.
*      WA_FINAL-DEBIT = WA_BSID-DMBTR.
      IF CURRENCY EQ 'USD' OR CURRENCY EQ 'EUR'.
        CLEAR : RATE,V_AMOUNT,DEB_AMT.
*      SELECT SINGLE UKURS FROM TCURR INTO RATE WHERE FCURR = 'INR' AND KURST = 'M' AND TCURR = CURRENCY.
*        RATE = RATE * -1.
        SELECT SINGLE KURSF FROM BKPF INTO RATE WHERE
                     BUKRS = WA_BSID-BUKRS AND BELNR = WA_BSID-BELNR AND GJAHR = WA_BSID-GJAHR.

        CALL FUNCTION 'CONVERT_CURRENCY_BY_RATE'
          EXPORTING
            FROM_AMOUNT   = WA_BSID-WRBTR                "WA_BSID-DMBTR
            FROM_CURRENCY = 'INR'
            FROM_FACTOR   = '1'
            RATE          = RATE
            TO_CURRENCY   = CURRENCY
            TO_FACTOR     = '1'
          IMPORTING
            TO_AMOUNT     = V_AMOUNT
*        EXCEPTIONS
*           NO_RATE_FOUND = 1
*           OTHERS        = 2
          .

*****      DEB_AMT = V_AMOUNT.     " * 10.
        WA_FINAL-DEBIT = WA_BSID-WRBTR.                 "DEB_AMT.
      ELSE.
        WA_FINAL-DEBIT = WA_BSID-WRBTR.                        "WA_BSID-DMBTR.
      ENDIF.


      READ TABLE IT_CUSTBAL INTO WA_CUSTBAL WITH KEY KUNNR = WA_FINAL-KUNNR.
      """""""""""""
      IF CURRENCY EQ 'USD' OR CURRENCY EQ 'EUR'.
        CLEAR : T_RATE,T_AMOUNT,VEND_BAL.
        SELECT SINGLE KURSF FROM BKPF INTO T_RATE WHERE
        BUKRS = WA_BSID-BUKRS AND BELNR = WA_BSID-BELNR AND GJAHR = WA_BSID-GJAHR.
*     T_RATE = T_RATE * -1.
        CALL FUNCTION 'CONVERT_CURRENCY_BY_RATE'
          EXPORTING
            FROM_AMOUNT   = WA_BSID-DMBTR
            FROM_CURRENCY = 'INR'
            FROM_FACTOR   = '1'
            RATE          = T_RATE
            TO_CURRENCY   = CURRENCY
            TO_FACTOR     = '1'
          IMPORTING
            TO_AMOUNT     = T_AMOUNT
*        EXCEPTIONS
*           NO_RATE_FOUND = 1
*           OTHERS        = 2
          .

        VEND_BAL = T_AMOUNT * 10.
        IF WA_BSID-SHKZG = 'S'.
**      WA_CUSTBAL-CLBAL = WA_CUSTBAL-CLBAL + VEND_BAL.
          WA_CUSTBAL-CLBAL = WA_CUSTBAL-CLBAL + WA_BSID-WRBTR..
        ELSEIF WA_BSID-SHKZG = 'H'.
**        WA_CUSTBAL-CLBAL = WA_CUSTBAL-CLBAL - VEND_BAL.
          WA_CUSTBAL-CLBAL = WA_CUSTBAL-CLBAL - WA_BSID-WRBTR.
        ENDIF.
        MODIFY IT_CUSTBAL FROM WA_CUSTBAL TRANSPORTING CLBAL WHERE KUNNR = WA_FINAL-KUNNR.
      ELSE.
        IF WA_BSID-SHKZG = 'S'.
**       WA_CUSTBAL-CLBAL = WA_CUSTBAL-CLBAL + WA_BSID-dmbtr.
          WA_CUSTBAL-CLBAL = WA_CUSTBAL-CLBAL + WA_BSID-WRBTR.
        ELSEIF WA_BSID-SHKZG = 'H'.
**         WA_CUSTBAL-CLBAL = WA_CUSTBAL-CLBAL - WA_BSID-dmbtr.
          WA_CUSTBAL-CLBAL = WA_CUSTBAL-CLBAL - WA_BSID-WRBTR.
        ENDIF.

        MODIFY IT_CUSTBAL FROM WA_CUSTBAL TRANSPORTING CLBAL WHERE KUNNR = WA_FINAL-KUNNR.
      ENDIF.
      """""""""
*      WA_CUSTBAL-CLBAL = WA_CUSTBAL-CLBAL + WA_BSID-DMBTR.
*      MODIFY IT_CUSTBAL FROM WA_CUSTBAL TRANSPORTING CLBAL WHERE KUNNR = WA_FINAL-KUNNR.
    ELSE.
*      WA_FINAL-CREDIT = WA_BSID-DMBTR.
      IF CURRENCY EQ 'USD' OR CURRENCY EQ 'EUR'.
        CLEAR : RATE,V_AMOUNT,DEB_AMT.
*      SELECT SINGLE UKURS FROM TCURR INTO RATE WHERE FCURR = 'INR' AND KURST = 'M' AND TCURR = CURRENCY.
*        RATE = RATE * -1.
        SELECT SINGLE KURSF FROM BKPF INTO RATE WHERE
                    BUKRS = WA_BSID-BUKRS AND BELNR = WA_BSID-BELNR AND GJAHR = WA_BSID-GJAHR.

        CALL FUNCTION 'CONVERT_CURRENCY_BY_RATE'
          EXPORTING
            FROM_AMOUNT   = WA_BSID-WRBTR                       " WA_BSID-DMBTR
            FROM_CURRENCY = 'INR'
            FROM_FACTOR   = '1'
            RATE          = RATE
            TO_CURRENCY   = CURRENCY
            TO_FACTOR     = '1'
          IMPORTING
            TO_AMOUNT     = V_AMOUNT
*        EXCEPTIONS
*           NO_RATE_FOUND = 1
*           OTHERS        = 2
          .

*****      DEB_AMT = V_AMOUNT . "* 10.
        WA_FINAL-DEBIT =  WA_BSID-WRBTR.  "DEB_AMT.
        WA_FINAL-DEBIT =  WA_FINAL-DEBIT * -1.
*       WA_FINAL-CREDIT = DEB_AMT.
      ELSE.
        WA_FINAL-DEBIT = - WA_BSID-WRBTR .                  "WA_BSID-DMBTR.

        "commented by sneha 29/05/2018
*       WA_FINAL-DEBIT = WA_FINAL-DEBIT * -1.

        "by sneha 29/05/2018
        WA_FINAL-CREDIT = WA_BSID-DMBTR.
        WA_FINAL-CREDIT = WA_FINAL-CREDIT * -1.
      ENDIF.


      READ TABLE IT_CUSTBAL INTO WA_CUSTBAL WITH KEY KUNNR = WA_FINAL-KUNNR.
      """"""""
      IF CURRENCY EQ 'USD' OR CURRENCY EQ 'EUR'.
        CLEAR : T_RATE,T_AMOUNT,VEND_BAL.
        SELECT SINGLE KURSF FROM BKPF INTO T_RATE WHERE
        BUKRS = WA_BSID-BUKRS AND BELNR = WA_BSID-BELNR AND GJAHR = WA_BSID-GJAHR.
*     T_RATE = T_RATE * -1.
        CALL FUNCTION 'CONVERT_CURRENCY_BY_RATE'
          EXPORTING
            FROM_AMOUNT   = WA_BSID-DMBTR
            FROM_CURRENCY = 'INR'
            FROM_FACTOR   = '1'
            RATE          = T_RATE
            TO_CURRENCY   = CURRENCY
            TO_FACTOR     = '1'
          IMPORTING
            TO_AMOUNT     = T_AMOUNT
*        EXCEPTIONS
*           NO_RATE_FOUND = 1
*           OTHERS        = 2
          .

        CUST_BAL = T_AMOUNT * 10.
**      WA_CUSTBAL-CLBAL = WA_CUSTBAL-CLBAL - CUST_BAL.
        WA_CUSTBAL-CLBAL = WA_CUSTBAL-CLBAL - WA_BSID-WRBTR.
        MODIFY IT_CUSTBAL FROM WA_CUSTBAL TRANSPORTING CLBAL WHERE KUNNR = WA_FINAL-KUNNR.
      ELSE.

        "uncommented
*     WA_CUSTBAL-CLBAL = WA_CUSTBAL-CLBAL - WA_BSID-dmbtr.
**      WA_CUSTBAL-CLBAL = WA_CUSTBAL-CLBAL - WA_BSID-dmbtr.
        WA_CUSTBAL-CLBAL = WA_CUSTBAL-CLBAL - WA_BSID-WRBTR.
        MODIFY IT_CUSTBAL FROM WA_CUSTBAL TRANSPORTING CLBAL WHERE KUNNR = WA_FINAL-KUNNR.
      ENDIF.
      """"""
*      WA_CUSTBAL-CLBAL = WA_CUSTBAL-CLBAL - WA_BSID-DMBTR.
*      MODIFY IT_CUSTBAL FROM WA_CUSTBAL TRANSPORTING CLBAL WHERE KUNNR = WA_FINAL-KUNNR.
    ENDIF.

    READ TABLE IT_BSEGCCPC INTO WA_BSEGCCPC WITH KEY BUKRS = WA_FINAL-BUKRS BELNR = WA_FINAL-BELNR GJAHR = WA_FINAL-GJAHR.
    IF WA_FINAL-KOSTL IS INITIAL AND WA_BSEGCCPC IS NOT INITIAL.
      WA_FINAL-KOSTL = WA_BSEGCCPC-KOSTL.
    ENDIF.
    IF WA_FINAL-PRCTR IS INITIAL AND WA_BSEGCCPC IS NOT INITIAL.
      WA_FINAL-PRCTR = WA_BSEGCCPC-PRCTR.
    ENDIF.

    IF WA_FINAL-KUNNR IS NOT INITIAL.
      READ TABLE IT_BSEGAC INTO WA_BSEGAC WITH KEY BUKRS = WA_FINAL-BUKRS BELNR = WA_FINAL-BELNR GJAHR = WA_FINAL-GJAHR.
      WA_FINAL-SAKNR = WA_BSEGAC-HKONT.

      WA_CUSTBAL-GJAHR = WA_BSEGAC-GJAHR .

      MODIFY IT_CUSTBAL FROM WA_CUSTBAL TRANSPORTING GJAHR WHERE KUNNR = WA_FINAL-KUNNR.

      READ TABLE IT_SKAT INTO WA_SKAT WITH KEY SAKNR = WA_FINAL-SAKNR.
      WA_FINAL-GLT20 = WA_SKAT-TXT20.
      WA_FINAL-GLT50 = WA_SKAT-TXT50.
      CLEAR WA_SKAT.
    ENDIF.

    READ TABLE IT_BKPF INTO WA_BKPF WITH KEY BUKRS = WA_FINAL-BUKRS BELNR = WA_FINAL-BELNR GJAHR = WA_FINAL-GJAHR.
    CALL FUNCTION 'FI_CONVERT_FIRSTCHARS_TOUPPER'
      EXPORTING
        INPUT_STRING  = WA_BKPF-BKTXT
        SEPARATORS    = ' -.,'
      IMPORTING
        OUTPUT_STRING = WA_FINAL-BKTXT.

    READ TABLE IT_SKAT INTO WA_SKAT WITH KEY SAKNR = WA_FINAL-HKONT.
    WA_FINAL-TXT20 = WA_SKAT-TXT20.
    WA_FINAL-TXT50 = WA_SKAT-TXT50.

    READ TABLE IT_KNA1 INTO WA_KNA1 WITH KEY KUNNR = WA_FINAL-KUNNR.
    WA_FINAL-NAME1 = WA_KNA1-NAME1.

    READ TABLE IT_PAYR INTO WA_PAYR WITH KEY ZBUKR = WA_FINAL-BUKRS VBLNR = WA_FINAL-BELNR GJAHR = WA_FINAL-GJAHR.
    WA_FINAL-CHECT = WA_PAYR-CHECT.

    READ TABLE IT_CSKT INTO WA_CSKT WITH KEY KOSTL = WA_FINAL-KOSTL.
    WA_FINAL-CNAME = WA_CSKT-KTEXT.

    READ TABLE IT_CEPCT INTO WA_CEPCT WITH KEY PRCTR = WA_FINAL-PRCTR.
    WA_FINAL-PNAME = WA_CEPCT-KTEXT.
*    READ TABLE IT_BSAD INTO WA_BSAD WITH KEY BELNR = WA_BSID-BELNR.
*    IF SY-SUBRC <> 0.
    APPEND WA_FINAL TO IT_FINAL.
*    ENDIF.


    CLEAR : WA_FINAL, WA_BSID, WA_BKPF, WA_BSEG, WA_KNA1, WA_SKAT, WA_PAYR, WA_CSKT, WA_CEPCT, WA_CUSTBAL.
  ENDLOOP.

  SORT IT_FINAL ASCENDING BY KUNNR BUDAT BELNR.


ENDFORM.                    "GET_DATA

*&---------------------------------------------------------------------*
*&      FORM  DISPLAY
*&---------------------------------------------------------------------*
*       TEXT
*----------------------------------------------------------------------*
FORM DISPLAY.

  DATA : LWA_PARAM       TYPE SFPOUTPUTPARAMS,
         LV_DOC_PARAMS   TYPE SFPDOCPARAMS,
         LS_FORM_OUTPUT  TYPE FPFORMOUTPUT,
         LV_XSTRING      TYPE XSTRING,
         CURRENCY        TYPE BSID-WAERS,
         LV_FUNCNAME     TYPE FUNCNAME,    ".
         LV_BIN_FILESIZE TYPE I,
         LT_PDF_CONTENT  TYPE SOLIX_TAB,
         WA_PACKING_LIST TYPE SOPCKLSTI1,
         LT_PACKING_LIST TYPE STANDARD TABLE OF SOPCKLSTI1.


  LWA_PARAM-DEVICE = 'PRINTER'.

  LWA_PARAM-DEST = 'LP01'.

  IF SY-UCOMM = 'PRNT'.

    LWA_PARAM-NODIALOG = 'X'.

    LWA_PARAM-PREVIEW = ''.

    LWA_PARAM-REQIMM = 'X'.

  ELSE.

    LWA_PARAM-NODIALOG = ''.

    LWA_PARAM-PREVIEW = 'X'.

  ENDIF.

  CALL FUNCTION 'FP_JOB_OPEN'
    CHANGING
      IE_OUTPUTPARAMS = LWA_PARAM
    EXCEPTIONS
      CANCEL          = 1
      USAGE_ERROR     = 2
      SYSTEM_ERROR    = 3
      INTERNAL_ERROR  = 4
      OTHERS          = 5.
  IF SY-SUBRC <> 0.
* Implement suitable error handling here
  ENDIF.

  CALL FUNCTION 'FP_FUNCTION_MODULE_NAME'
    EXPORTING
      I_NAME     = 'ZIN1_ACCOUNT_STATEMENT_CUST_N'
    IMPORTING
      E_FUNCNAME = LV_FUNCNAME
*     E_INTERFACE_TYPE           =
*     EV_FUNCNAME_INBOUND        =
    .


  IF CHKB = 'X'.

*--------------------------------------------------------------------*
    LOOP AT R_CUSTNO INTO LS_CUSTNO.
      LOOP AT IT_CUSTBAL INTO WA_CUSTBAL WHERE KUNNR = LS_CUSTNO-LOW.
        REFRESH : IT_FINAL_COPY[], IT_CUSTBAL_COPY[].
        CLEAR : TAB_OTF_DATA.
        APPEND WA_CUSTBAL TO IT_CUSTBAL_COPY.
        LOOP AT IT_FINAL INTO WA_FINAL WHERE KUNNR = WA_CUSTBAL-KUNNR.
          APPEND WA_FINAL TO IT_FINAL_COPY.
          CLEAR WA_FINAL.
        ENDLOOP.
*--------------------------------------------------------------------*
      CLEAR: LV_DOC_PARAMS, CPARAM.
        CPARAM-NO_DIALOG = 'X'.
        CPARAM-GETOTF = 'X'.

        CALL FUNCTION LV_FUNCNAME   "'/1BCDWB/SM00000072'
          EXPORTING
            /1BCDWB/DOCPARAMS  = LV_DOC_PARAMS
            IT_FINAL           = IT_FINAL_COPY
            IT_CUSTBAL         = IT_CUSTBAL_COPY
            CURRENCY           = CURRENCY
          IMPORTING
            /1BCDWB/FORMOUTPUT = LS_FORM_OUTPUT
          EXCEPTIONS
            USAGE_ERROR        = 1
            SYSTEM_ERROR       = 2
            INTERNAL_ERROR     = 3
            OTHERS             = 4.
        IF SY-SUBRC <> 0.
* Implement suitable error handling here
        ENDIF.

*        CALL FUNCTION 'FP_JOB_CLOSE'
** IMPORTING
**   E_RESULT             =
*          EXCEPTIONS
*            USAGE_ERROR    = 1
*            SYSTEM_ERROR   = 2
*            INTERNAL_ERROR = 3
*            OTHERS         = 4.
*        IF SY-SUBRC <> 0.
** Implement suitable error handling here
*        ENDIF.
        LV_XSTRING = LS_FORM_OUTPUT-PDF.


        CALL FUNCTION 'SCMS_XSTRING_TO_BINARY'      "VE
          EXPORTING
            BUFFER          = LV_XSTRING
            APPEND_TO_TABLE = ' '
          IMPORTING
            OUTPUT_LENGTH   = LV_BIN_FILESIZE
          TABLES
            BINARY_TAB      = LT_BCS_PDF.



*wait UP TO 10 SECONDS.
* ATTACHMENT
        REFRESH: I_RECLIST,
        I_OBJTXT,
        I_OBJBIN,
        I_OBJPACK.
        CLEAR : WA_OBJHEAD ,DATE,SUBJECT,SUBJECT.
        I_OBJBIN[] = I_RECORD[].


************Added by DH 15.09.22
        CALL FUNCTION 'CONVERSION_EXIT_IDATE_OUTPUT'
          EXPORTING
            INPUT  = POSTDATE
          IMPORTING
            OUTPUT = POSTDATE1.

        CONCATENATE 'Please find the attached PDF copy of Balance Confirmation as on' POSTDATE1 '.' INTO LV_TEXT SEPARATED BY SPACE.
        I_OBJTXT = LV_TEXT.
        APPEND I_OBJTXT.
*************************

        DESCRIBE TABLE I_OBJTXT LINES V_LINES_TXT.
        READ TABLE I_OBJTXT INDEX V_LINES_TXT.
        WA_DOC_CHNG-OBJ_NAME = 'SMARTFORM'.
        WA_DOC_CHNG-EXPIRY_DAT = SY-DATUM + 0.
        WA_DOC_CHNG-OBJ_DESCR = 'Balance Confirmation'. "subject . "'CHECK LETTER'.
        WA_DOC_CHNG-SENSITIVTY = 'F'.
        WA_DOC_CHNG-DOC_SIZE = V_LINES_TXT * 255.
* MAIN TEXT
        CLEAR I_OBJPACK-TRANSF_BIN.
        I_OBJPACK-HEAD_START = 1.
        I_OBJPACK-HEAD_NUM = 0.
        I_OBJPACK-BODY_START = 1.
        I_OBJPACK-BODY_NUM = V_LINES_TXT.
        I_OBJPACK-DOC_TYPE = 'RAW'.
        APPEND I_OBJPACK.
* ATTACHMENT (PDF-ATTACHMENT)
        I_OBJPACK-TRANSF_BIN = 'X'.
        I_OBJPACK-HEAD_START = 1.
        I_OBJPACK-HEAD_NUM = 0.
        I_OBJPACK-BODY_START = 1.
        DESCRIBE TABLE I_OBJBIN LINES V_LINES_BIN.
        READ TABLE I_OBJBIN INDEX V_LINES_BIN.
        I_OBJPACK-DOC_SIZE = V_LINES_BIN * 255 .
        I_OBJPACK-BODY_NUM = V_LINES_BIN.
        I_OBJPACK-DOC_TYPE = 'PDF'.
        I_OBJPACK-OBJ_NAME = 'SMART'.
        I_OBJPACK-OBJ_DESCR = ATTACH . "'TEST'.
        APPEND I_OBJPACK.

        CLEAR I_RECLIST.
        CLEAR: LV_ADRNR, LV_SMTP_ADDR.
        SELECT SINGLE ADRNR
                      FROM KNA1
                      INTO LV_ADRNR
                      WHERE KUNNR = WA_CUSTBAL-KUNNR."custno-low.

        SELECT SINGLE SMTP_ADDR
                      FROM ADR6
                      INTO LV_SMTP_ADDR
                      WHERE ADDRNUMBER = LV_ADRNR.
        IF LV_SMTP_ADDR IS NOT INITIAL .
          I_RECLIST-RECEIVER = LV_SMTP_ADDR. "'mkhasbag@delvalflow.com'. "'diksha.halve@primustechsys.com'.  "'mkhasbag@delvalflow.com'.  "'diksha.halve@primustechsys.com'.
          "lv_smtp_addr."w_adr6-smtp_addr."'RAJENDRA.PATHAK@COOPERCORP.IN'.
          I_RECLIST-REC_TYPE = 'U'.
          APPEND I_RECLIST.

***********************ADDED BY JYOTI ON 12.02.2025***********************
          SELECT * FROM ZCONF_MAIL INTO TABLE @DATA(IT_MAIL).
          IF IT_MAIL IS NOT INITIAL.
            LOOP AT IT_MAIL INTO DATA(WA_MAIL).
              I_RECLIST-RECEIVER = WA_MAIL-ZMAIL_ID.
              I_RECLIST-REC_TYPE = 'U'.
              I_RECLIST-COPY = 'X'.
              APPEND I_RECLIST.
              CLEAR: WA_MAIL.
            ENDLOOP.
          ENDIF.

          PERFORM SEND_MAIL .

* insert start log message
          GS_MSG-MSGTY = 'S'.
          GS_MSG-MSGID = 'ZFI_CONF'.
          GS_MSG-MSGNO = '007'.
          GS_MSG-MSGV1 = LS_CUSTNO-LOW.
          APPEND GS_MSG TO GT_MSG.
          CLEAR GS_MSG.

          CONCATENATE 'Balance confirmation is succesfully, generated mail send to Customer ' LS_CUSTNO-LOW
          INTO GS_MESSAGE-MSG_TXT SEPARATED BY SPACE.
          GS_MESSAGE-MSG_TYP = '@08@'.
          APPEND GS_MESSAGE TO GT_MESSAGE.

          CLEAR GS_MESSAGE .

        ELSE.
* Insert start log message
          GS_MSG-MSGTY = 'E'.
          GS_MSG-MSGID = 'ZFI_CONF'.
          GS_MSG-MSGNO = '006'.
          GS_MSG-MSGV1 = LS_CUSTNO-LOW.
          APPEND GS_MSG TO GT_MSG.
          CLEAR GS_MSG.


          CONCATENATE 'Mail ID does not exist againts Customer ' LS_CUSTNO-LOW
          INTO GS_MESSAGE-MSG_TXT SEPARATED BY SPACE.
          GS_MESSAGE-MSG_TYP = '@0A@'.
          APPEND GS_MESSAGE TO GT_MESSAGE.
          CLEAR GS_MESSAGE .

        ENDIF.

      ENDLOOP.
      IF SY-SUBRC EQ 4.
* Insert start log message
        GS_MSG-MSGTY = 'E'.
        GS_MSG-MSGID = 'ZFI_CONF'.
        GS_MSG-MSGNO = '005'.
        GS_MSG-MSGV1 = LS_CUSTNO-LOW.
        APPEND GS_MSG TO GT_MSG.
        CLEAR GS_MSG.

        CONCATENATE 'Balance does not exits against Customer' LS_CUSTNO-LOW
        INTO GS_MESSAGE-MSG_TXT SEPARATED BY SPACE.
        GS_MESSAGE-MSG_TYP = '@0A@'.
        APPEND GS_MESSAGE TO GT_MESSAGE.
        CLEAR GS_MESSAGE .
      ENDIF.

    ENDLOOP.

    CALL FUNCTION 'FP_JOB_CLOSE'
* IMPORTING
*   E_RESULT             =
          EXCEPTIONS
            USAGE_ERROR    = 1
            SYSTEM_ERROR   = 2
            INTERNAL_ERROR = 3
            OTHERS         = 4.
        IF SY-SUBRC <> 0.
* Implement suitable error handling here
        ENDIF.

  ELSE.

    IF IT_CUSTBAL IS NOT INITIAL.

      CALL FUNCTION LV_FUNCNAME   "'/1BCDWB/SM00000072'
        EXPORTING
          /1BCDWB/DOCPARAMS  = LV_DOC_PARAMS
          IT_FINAL           = IT_FINAL
          IT_CUSTBAL         = IT_CUSTBAL
          CURRENCY           = CURRENCY
        IMPORTING
          /1BCDWB/FORMOUTPUT = LS_FORM_OUTPUT
        EXCEPTIONS
          USAGE_ERROR        = 1
          SYSTEM_ERROR       = 2
          INTERNAL_ERROR     = 3
          OTHERS             = 4.
      IF SY-SUBRC <> 0.
* Implement suitable error handling here
      ENDIF.

      CALL FUNCTION 'FP_JOB_CLOSE'
* IMPORTING
*   E_RESULT             =
        EXCEPTIONS
          USAGE_ERROR    = 1
          SYSTEM_ERROR   = 2
          INTERNAL_ERROR = 3
          OTHERS         = 4.
      IF SY-SUBRC <> 0.
* Implement suitable error handling here
      ENDIF.


    ELSE.

      MESSAGE 'Balance does not exits against customer' TYPE 'S' DISPLAY LIKE 'E'. .
    ENDIF.
  ENDIF.


  IF CHKB = 'X'.
*LOG genrated! Please check SLG1 for detailed logs.
    PERFORM SLG0_LOG.
*Dispaly output IN ALV
    PERFORM DISPLAY_ALV.
  ENDIF.



  REFRESH: I_RECLIST,
  I_OBJTXT,
  I_OBJBIN,
  I_OBJPACK.


ENDFORM.                    " DISPLAY_DATA
*&---------------------------------------------------------------------*
*&      Form  DISPLAY_ALV
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM DISPLAY_ALV .
*&---------------------------------------------------------------------*
*& Data Declaration
*&---------------------------------------------------------------------*
  DATA: LT_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV,
        LS_FIELDCAT TYPE SLIS_FIELDCAT_ALV.
*&---------------------------------------------------------------------*
*& Build field catalog
*&---------------------------------------------------------------------*

  LS_FIELDCAT-FIELDNAME  = 'MSG_TYP'.    " Message type
  LS_FIELDCAT-SELTEXT_M  = 'Message type'."text-010.     " Message text
  LS_FIELDCAT-OUTPUTLEN = '12'.
  APPEND LS_FIELDCAT TO LT_FIELDCAT.

  LS_FIELDCAT-FIELDNAME  = 'MSG_TXT'.
  LS_FIELDCAT-SELTEXT_M  = 'Message text' ."text-011.
  LS_FIELDCAT-OUTPUTLEN = '80'.
  APPEND LS_FIELDCAT TO LT_FIELDCAT.

*Pass data and field catalog to ALV function module to display ALV list
  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
    EXPORTING
      IT_FIELDCAT   = LT_FIELDCAT
    TABLES
      T_OUTTAB      = GT_MESSAGE
    EXCEPTIONS
      PROGRAM_ERROR = 1
      OTHERS        = 2.

ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  SLG0_LOG
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM SLG0_LOG .
*Application Log object & Subobject
  LV_OBJ = 'ZFI_CONF'.

* Header information for the log
  LS_HEADER-OBJECT     = LV_OBJ.
  LS_HEADER-ALDATE     = SY-DATUM.
  LS_HEADER-ALTIME     = SY-UZEIT.
  LS_HEADER-ALUSER     = SY-UNAME.


* Get the Log handle using the header
  CALL FUNCTION 'APPL_LOG_WRITE_HEADER'
    EXPORTING
      HEADER              = LS_HEADER
    IMPORTING
      E_LOG_HANDLE        = LV_LOG_HANDLE
    EXCEPTIONS
      OBJECT_NOT_FOUND    = 1
      SUBOBJECT_NOT_FOUND = 2
      ERROR               = 3
      OTHERS              = 4.
  IF SY-SUBRC <> 0.
    "Message Text: Error while writing Log header data.
    GS_MSG-MSGTY = 'E'.
    GS_MSG-MSGID = 'ZFI_CONF'.
    GS_MSG-MSGNO = '004'.
    APPEND GS_MSG TO GT_MSG.


  ENDIF.

* Get the next avalaible Log number
  CALL FUNCTION 'BAL_DB_LOGNUMBER_GET'
    EXPORTING
      I_CLIENT                 = SY-MANDT
      I_LOG_HANDLE             = LV_LOG_HANDLE
    IMPORTING
      E_LOGNUMBER              = LV_LOG_NUMBER
    EXCEPTIONS
      LOG_NOT_FOUND            = 1
      LOGNUMBER_ALREADY_EXISTS = 2
      NUMBERING_ERROR          = 3
      OTHERS                   = 4.
  IF SY-SUBRC <> 0.
    "Message Text: Next available Log number not generated.
*        gs_msg-msgty = 'E'.
*        gs_msg-msgid = 'ZFI_CONF'.
*        gs_msg-msgno = '001'.
*        APPEND gs_msg TO gt_msg.


  ENDIF.


* write the Log messages to the memory
  CALL FUNCTION 'APPL_LOG_WRITE_MESSAGES'
    EXPORTING
      OBJECT              = LV_OBJ
      LOG_HANDLE          = LV_LOG_HANDLE
    TABLES
      MESSAGES            = GT_MSG
    EXCEPTIONS
      OBJECT_NOT_FOUND    = 1
      SUBOBJECT_NOT_FOUND = 2
      OTHERS              = 3.
  IF SY-SUBRC <> 0.
    "Message Text: Log not found (in main memory).
    GS_MSG-MSGTY = 'E'.
    GS_MSG-MSGID = 'BL'.
    GS_MSG-MSGNO = '207'.
    APPEND GS_MSG TO GT_MSG.


  ENDIF.

* write the log message to Database which can be later analyzed from transaction SLG1
  MOVE-CORRESPONDING LS_HEADER TO LS_LOGNUM.
  LS_LOGNUM-LOGNUMBER = LV_LOG_NUMBER.
  APPEND LS_LOGNUM TO LT_LOGNUM.

  CALL FUNCTION 'APPL_LOG_WRITE_DB'
    EXPORTING
      OBJECT                = LV_OBJ
      LOG_HANDLE            = LV_LOG_HANDLE
    TABLES
      OBJECT_WITH_LOGNUMBER = LT_LOGNUM
    EXCEPTIONS
      OBJECT_NOT_FOUND      = 1
      SUBOBJECT_NOT_FOUND   = 2
      INTERNAL_ERROR        = 3
      OTHERS                = 4.
  IF SY-SUBRC <> 0.
    "Message Text: No log was created for object &.
    GS_MSG-MSGTY = 'E'.
    GS_MSG-MSGID = 'BL'.
    GS_MSG-MSGNO = '007'.
    GS_MSG-MSGV1 = LV_OBJ.
    APPEND GS_MSG TO GT_MSG.
    CLEAR : GS_MSG.


  ENDIF.

ENDFORM.
*&---------------------------------------------------------------------*
*& Form send_mail
*&---------------------------------------------------------------------*
*& text
*&---------------------------------------------------------------------*
*& -->  p1        text
*& <--  p2        text
*&---------------------------------------------------------------------*
FORM SEND_MAIL .
  DATA: LX_DOCUMENT_BCS TYPE REF TO CX_DOCUMENT_BCS VALUE IS INITIAL.
  CLASS CL_BCS DEFINITION LOAD.

  DATA: LO_SEND_REQUEST TYPE REF TO CL_BCS VALUE IS INITIAL.
  LO_SEND_REQUEST = CL_BCS=>CREATE_PERSISTENT( ).

* Message body and subject

  DATA: LT_MESSAGE_BODY TYPE BCSY_TEXT VALUE IS INITIAL,
        LO_DOCUMENT     TYPE REF TO CL_DOCUMENT_BCS VALUE IS INITIAL,
        WA_BODY         TYPE SOLI.

  APPEND 'Dear Sir/Madam,' TO LT_MESSAGE_BODY.
  APPEND ' ' TO LT_MESSAGE_BODY.

  WA_BODY-LINE = LV_TEXT .

  APPEND WA_BODY TO LT_MESSAGE_BODY .

  APPEND ' ' TO LT_MESSAGE_BODY.
  APPEND ' ' TO LT_MESSAGE_BODY.

  APPEND 'Thanks & Regards,' TO LT_MESSAGE_BODY.
  APPEND 'DELVAL Flow Controls Pvt Ltd' TO LT_MESSAGE_BODY.



  LO_DOCUMENT = CL_DOCUMENT_BCS=>CREATE_DOCUMENT(
    I_TYPE    = 'RAW'
    I_TEXT    = LT_MESSAGE_BODY
    I_SUBJECT = 'Balance Confirmation' ).


  TRY.

      LO_DOCUMENT->ADD_ATTACHMENT(
        EXPORTING
          I_ATTACHMENT_TYPE    = 'PDF'
          I_ATTACHMENT_SUBJECT = 'Balance Confirmation'
          I_ATT_CONTENT_HEX    = LT_BCS_PDF ).

    CATCH CX_DOCUMENT_BCS INTO LX_DOCUMENT_BCS.

  ENDTRY.
  LO_SEND_REQUEST->SET_DOCUMENT( LO_DOCUMENT ).

  DATA: LO_SENDER TYPE REF TO IF_SENDER_BCS VALUE IS INITIAL,

        L_SEND    TYPE ADR6-SMTP_ADDR.

  LO_SENDER = CL_CAM_ADDRESS_BCS=>CREATE_INTERNET_ADDRESS( 'balance.confirmation@delvalflow.com' ).

*  lo_sender = cl_sapuser_bcs=>create( sy-uname ).

* Set sender

  LO_SEND_REQUEST->SET_SENDER(
    EXPORTING
      I_SENDER = LO_SENDER ).


  DATA:

  LO_RECIPIENT TYPE REF TO IF_RECIPIENT_BCS VALUE IS INITIAL.


  IF I_RECLIST IS NOT INITIAL .
    LOOP AT I_RECLIST INTO DATA(W_REC).
      CLEAR : LV_SMTP_ADDR.
      LV_SMTP_ADDR = W_REC-RECEIVER .


      LO_RECIPIENT = CL_CAM_ADDRESS_BCS=>CREATE_INTERNET_ADDRESS( LV_SMTP_ADDR ).
      IF   W_REC-COPY EQ SPACE .
** Set recipient
        LO_SEND_REQUEST->ADD_RECIPIENT(
          EXPORTING
            I_RECIPIENT = LO_RECIPIENT
            I_EXPRESS   = 'X' ).

      ELSE.

        LO_SEND_REQUEST->ADD_RECIPIENT(
          EXPORTING
            I_RECIPIENT = LO_RECIPIENT
            I_COPY      = 'X'
            I_EXPRESS   = 'X' ).

      ENDIF.
      CLEAR : W_REC .
    ENDLOOP.

*  lo_send_request->add_recipient(

*  EXPORTING

*  i_recipient = lo_recipient

*  i_express = 'X' ).

* Send email

    DATA: LV_SENT_TO_ALL(1) TYPE C VALUE IS INITIAL.

    LO_SEND_REQUEST->SEND(
      EXPORTING
        I_WITH_ERROR_SCREEN = 'X'
      RECEIVING
        RESULT              = LV_SENT_TO_ALL ).

    COMMIT WORK.

  ENDIF.
ENDFORM.
